### ISSUE TITLE
[Article Designs] Create an article design for "Oracles and MARKET Protocol"

### ISSUE THREAD

**Issue by lakikentaki** [MARKETProtocol/assets#1]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the workflow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: We want to have a graphic that illustrates the story within the article.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Description
[comment]: # (Describe what actually happened.)
For this particular article, I don't have a clear idea on how the graphic should look like, but I have one example that illustrates how external data is brought onto the blockchain via oracles. So something in that fashion would probably be suitable. 
### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:

By following the description and design example provided in the additional information, please create the graphic for the mentioned article and upload the visual asset into its destination folder.

### Deadline
July 30th, 2018
### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

Design example: http://surprizingfacts.com/wp-content/uploads/2017/07/oracle-applications-or-how-to-become-a-useful-smart-contract-geektimes.png

**Comment by nitinrgupta** [comment]
@lakikentaki Let me know what you think on these two options.
1 - <img width="962" alt="screen shot 2018-07-27 at 6 19 46 pm" src="https://user-images.githubusercontent.com/4952395/43322407-fb22ce26-91cb-11e8-8741-3db39ff8bdca.png">

2 - 
<img width="1107" alt="screen shot 2018-07-27 at 6 19 40 pm" src="https://user-images.githubusercontent.com/4952395/43322418-03c8664e-91cc-11e8-999a-1d0714e9af1c.png">

**Comment by lakikentaki** [comment]
They both look great, I will probably go with number 2 👍
