### ISSUE TITLE
[Article Designs] Create a graphic for "Cryptocurrency - Beyond Currency 

### ISSUE THREAD

**Issue by lakikentaki** [MARKETProtocol/assets#2]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the workflow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happen)
*Summary*: We want to have a graphic that illustrates the story within the article.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Description
[comment]: # (Describe what actually happened.)
For this particular article, I think that something that would best illustrate the transition from Blockchain 1.0 (bitcoin), to blockchain 2.0  (smart contracts, altcoins), to blockchain 3.0 (interoperability) would be the most appropriate design. The examples provided are not the best ones, unfortunately, since I haven't seen anyone exploring this topic visually in such depth. 
### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:

By following the description and design example provided in the additional information, please create the graphic for the mentioned article and upload the visual asset into its destination folder.

### Deadline
August 17th, 2018
### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

Design examples:
![arcblock-3 0](https://user-images.githubusercontent.com/39289842/42968793-effa65da-8b69-11e8-9925-49e4b7e35313.png)

![blockchain-evolution1](https://user-images.githubusercontent.com/39289842/42968794-f0091198-8b69-11e8-9ab7-af0aaf1667a9.png)

**Comment by pelsasser** [comment]
@nitinrgupta - where you able to get this done for @lakikentaki

**Comment by pelsasser** [comment]
@lakikentaki - @auregimon is gonna handle this also
