### ISSUE TITLE
[YouTube] Create a new Engineering Weekly Thumbnail

### ISSUE THREAD

**Issue by lakikentaki** [MARKETProtocol/assets#3]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the workflow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happen)
*Summary*: We want to have a graphic that includes a world map and different time zones displayed

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:

By following the design example provided in the additional information, please create the graphic for the YouTube Engineering Weekly Thumbnail following our current branding guidelines

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

Example: 

![origin_engineering_call](https://user-images.githubusercontent.com/39289842/44226254-39464a00-a155-11e8-9166-b0f39c558a72.png)

Current Thumbnail: 

![engineeringweeklythursdaythumbnail jpeg 001](https://user-images.githubusercontent.com/39289842/44226283-4e22dd80-a155-11e8-96c7-3a5617e85f5d.jpeg)

**Comment by pelsasser** [comment]
@auregimon is working on this @lakikentaki
